"""Add custom_models field to credentials

Revision ID: 1cff5253252b
Revises: 45af224f3156
Create Date: 2025-09-23 19:07:02.715573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cff5253252b'
down_revision: Union[str, None] = '45af224f3156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credentials', sa.Column('custom_models', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credentials', 'custom_models')
    # ### end Alembic commands ###
